### ISSUE TITLE
Configmap

### ISSUE THREAD

**Issue by markjacksonfishing** [andrewpsp/the_kube_way#1]
Should there be an associated configmap for the variables I am seeing? Also would it make sense to wrap this in a deployment yml for better automation? If you think so, I forked this repo and will create and open a PR. Thoughts?

**Comment by markjacksonfishing** [comment]
I am going to suggest somethings in a PR and you can decide. I will have it in before the days end

**Comment by andrewpsp** [comment]
The base image from the Dockerfile and ConfigMaps associated with the variables  are not public resources and needs to be updated.
